### ISSUE TITLE
Rename Elements

### ISSUE THREAD

**Issue by jjcamp** [jjcamp/mdgt#4]
The term _element_ was chosen as a way to name the JSON files which tell **mdgt** where to retrieve and how to parse different kinds of microdata.  Although _elements_ are unique enough in naming to distinguish themselves from python's _modules_ or possible future _add-ins_ or _extensions_, it is also not a term that is normally associated with files of this nature.

Current possibilities:
- **element** - _current term_
- **pak** - _from @narrative_
- **provider** - _from @narrative, my favorite thus far_
- **source** - _from @narrative_
- **transformer** - _from @stevensona_
- **hook** - _from @stevensona_
- **binding** - _from @stevensona_
- **contract** - _from @stevensona_

**Comment by eriknstevenson** [comment]
Couple other things you might consider:
- provider
- source

**Comment by jjcamp** [comment]
@narrative those are great, I will add them to the list.

**Comment by stevensona** [comment]
_transformer_, _hook_, _binding_, _contract_

**Comment by jjcamp** [comment]
Renamed to _provider_ in commit 3203ed2.
