### ISSUE TITLE
Add optional configuration file

### ISSUE THREAD

**Issue by jjcamp** [jjcamp/mdgt#8]
A small configuration file should be usable so that common configuration items do not need to be passed via the command line every time mdgt is started.

**Comment by rmed** [comment]
Hi, what items were you thinking on including in this configuration file? Also, should it have a predefined location (like the user's home directory or the current working directory) or be specified when calling mdgt?

**Comment by jjcamp** [comment]
I was thinking that every option available other than the provider and the query should be available, with mdgt looking for _default.json_ in the CWD but optionally passed in on the command line with --config (-f).

So mdgt will first read the command-line arguments, then if no configuration file is specified, look for _default.json_ in the CWD.  If a configuration file is found, then any command-line arguments will override the configuration file.

I suggest json as the configuration file format only because it is supported by the `configparser` module, which is by no means required for the implementation.

**Comment by rmed** [comment]
I'd suggest using the INI structure shown in the Python documentation (https://docs.python.org/3/library/configparser.html), in particular because it is easier for humans to write. Therefore it could try to search for something like `CWD/mdgt.conf` and act according to what you have specified.

**Comment by jjcamp** [comment]
Sounds fine to me.
